### ISSUE TITLE
Table & full styling

### ISSUE THREAD

**Issue by pylover** [pylover/yml2pdf#4]

**Comment by memlucky71** [comment]
@pylover , what's your opinion about this yaml structure for table element?

Header1 | Header2 \n Header2 subtitle
--- | ---
Value1 | Value2

for the above table structure: 

```
  - !Table
    data:
      -
        -
          - !Paragraph
            text: 'Header1'
            styles:
              text_color: '#FF0000'
        - <- WHAT IS THIS?
          - !Paragraph
            text: 'Header2'
            styles:
              text_color: '#FF0000'
          - !Paragraph
            text: 'Header2 subtitle'
            styles:
              text_color: '#FF0000'       
      -
        -
          - !Paragraph
            text: 'Value1'
        -
          - !Paragraph
            text: 'Value2'
```

**Comment by pylover** [comment]
What is the additional `-` lines?

**Comment by pylover** [comment]
I prefer this schema:

```yaml

- !Table
  header:
     - !Column
     - !Column

  body:
      - !Row
         _ !Cell
         _ !Cell

      - !Row
         _ !Cell
         _ !Cell
  
```
